# -*- coding: utf-8 -*-
"""Amazon Sales Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GPnnn8ZI0knPlfriUPNUepaAc7lXxHKi
"""

import pandas as pd

# Load the dataset
file_path = "/content/Amazon Sales data.csv"
df = pd.read_csv(file_path)

# Data Quality Assessment
print("Data Quality Assessment:")
print(df.info())  # Summary of the dataset including data types and missing values
print("\n")

# Data Cleaning
# Convert 'Order Date' column to datetime format
df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce')

# Drop rows with missing values in 'Order Date' column
df.dropna(subset=['Order Date'], inplace=True)

# Extract Year, Month, and Year-Month
df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month
df['Year-Month'] = df['Order Date'].dt.to_period('M')

# Display all data
print(df)

# Sales Trend Analysis
# Month-wise Sales
monthly_sales = df.groupby('Month')['Total Revenue'].sum()

# Year-wise Sales
yearly_sales = df.groupby('Year')['Total Revenue'].sum()

# Year-Month-wise Sales
year_monthly_sales = df.groupby('Year-Month')['Total Revenue'].sum()

print(monthly_sales)

print(yearly_sales)

print(year_monthly_sales)

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Monthly Sales Visualization
plt.figure(figsize=(10, 6))
sns.barplot(x=monthly_sales.index, y=monthly_sales.values)
plt.title('Monthly Sales')
plt.xlabel('Month')
plt.ylabel('Total Revenue')
plt.show()

# Yearly Sales Visualization
plt.figure(figsize=(10, 6))
sns.lineplot(x=yearly_sales.index, y=yearly_sales.values)
plt.title('Yearly Sales')
plt.xlabel('Year')
plt.ylabel('Total Revenue')
plt.show()

# Year-Month Sales Visualization
fig = px.line(x=year_monthly_sales.index.astype(str), y=year_monthly_sales.values,
              labels={'x': 'Year-Month', 'y': 'Total Revenue'}, title='Year-Month Sales')
fig.show()

import plotly.graph_objects as go

# Dashboard Construction
# We can create an interactive dashboard using Plotly
# For simplicity, let's construct a basic dashboard with the three visualizations

# Create trace for Monthly Sales
trace_monthly_sales = go.Bar(x=monthly_sales.index, y=monthly_sales.values, name="Monthly Sales")

# Create trace for Yearly Sales
trace_yearly_sales = go.Scatter(x=yearly_sales.index, y=yearly_sales.values, mode="lines", name="Yearly Sales")

# Create trace for Year-Month Sales
trace_year_monthly_sales = go.Scatter(x=year_monthly_sales.index.astype(str), y=year_monthly_sales.values, mode="lines", name="Year-Month Sales")

# Dashboard layout
dashboard_layout = go.Layout(
    title="Amazon Sales Dashboard",
    xaxis=dict(title="Time"),
    yaxis=dict(title="Total Revenue")
)

# Construct the dashboard
fig = go.Figure(data=[trace_monthly_sales, trace_yearly_sales, trace_year_monthly_sales], layout=dashboard_layout)

# Display the dashboard
fig.show()







